Areas/PrivatePages/Controllers/NewProductController.cs
using shoptraicay.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shoptraicay.Areas.PrivatePages.Controllers
{
    public class NewProductController : Controller
    {
        // GET: PrivatePages/NewProduct
        public ActionResult Index()
        {
            SanPham x = new SanPham();
            x.ngayDang = DateTime.Now;
            DangNhap dn = Session["tkDangNhap"] as DangNhap;
            x.taiKhoan = dn.taiKhoan;
            x.daDuyet = false;
            return View(x);
        }
        [HttpPost]
        public ActionResult Index(SanPham x,int loaiSP, HttpPostedFileBase hinhSP)
        {
            try
            {
                ShoptraicayEntities shop = new ShoptraicayEntities();

                x.daDuyet = false;
                x.maSP = string.Format("{0:yyMMddhhmm}", DateTime.Now);
                x.ngayDang = DateTime.Now;
                x.giamGia = 0;
                x.dvt = "kg";
                x.maLoai = loaiSP;
                DangNhap tk = Session["tkDangNhap"] as DangNhap;
                x.taiKhoan = tk.taiKhoan;

                if (hinhSP != null)
                {
                    //Vị trí lưu hình
                    string virPath = "/Assets/Images/CacSPMoi/";
                    string phyPath = Server.MapPath("~/" + virPath);
                    string EXT = Path.GetExtension(hinhSP.FileName);
                    string nameF = "HDD" + x.maSP + EXT;
                    hinhSP.SaveAs(phyPath + nameF);
                    x.hinhDD = virPath + nameF;
                    ViewBag.HinhMH = x.hinhDD;
                    shop.SanPham.Add(x);
                }
                else
                    x.hinhDD = "";
                shop.SaveChanges();
                return RedirectToAction("Index", "Products");
            }
            catch
            {

            }
            return View();
        }
    }
}

Areas/PrivatePages/Views/NewProduct/Index.cshtml
@model shoptraicay.Models.SanPham
@using shoptraicay.Models
@{
    ViewBag.Title = "Index";
    List<LoaiSP> loaiSPs = Common.GetLoaiSPs();
    Layout = "~/Areas/PrivatePages/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thông tin sản phẩm mới</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Sản phẩm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@using (Html.BeginForm("Index", "NewProduct", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row container-fluid">
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Thông tin chính</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên Sản phẩm</label>
                            @Html.TextBoxFor(m => m.tenSP, new { @class = "form-control", @placeholder = "Nhập tên sản phẩm" })
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <label for="ndtt">Nội dung tóm tắt</label>
                                @Html.TextAreaFor(m => m.ndTomTat, new { @rows = "5", @class = "form-control", @placeholder = "Nội dung tóm tắt..." })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <label for="ndtt">Nội dung</label>
                                @Html.TextAreaFor(m => m.noiDung, new { @rows = "7", @class = "form-control", @style = "margin: 0 7px;", @id = "ndBaiViet1", @placeholder = "Mô tả về sản phẩm..." })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Giá bán/kg</label>
                            @Html.TextBoxFor(m => m.giaBan, new { @class = "form-control", @placeholder = "Giá bán của sản phẩm" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Mã loại", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <select name="loaiSP" class="form-control">
                                    @foreach (LoaiSP l in loaiSPs)
                                    {
                                        <option value="@l.maLoai">@l.tenLoai</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="exampleInputEmail1">Ngày đăng</label>
                                @Html.TextBoxFor(m => m.ngayDang, new { @class = "form-control", @disabled = "disabled" })
                            </div>
                            <div class="form-group col-md-6">
                                <label for="exampleInputEmail1">Tài khoản</label>
                                @Html.TextBoxFor(m => m.taiKhoan, new { @class = "form-control", @disabled = "disabled" })
                            </div>
                            <div class="form-group col-md-6">
                                <label>Đã duyệt</label>
                                @Html.TextBoxFor(m => m.daDuyet, new { @disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </form>
            </div>
            <!-- /.card -->
        </div>

        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Hình minh họa cho sản phẩm</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <img style="height: 288px;" src="http://gxtanhuong.net/wp-content/uploads/2016/04/Tao001-2.jpg" />
                    <label for="exampleInputFile" style=" width: 100%;">File input</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="hinhSP">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text" id="">Upload</span>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <div class="card-footer" style="width: 100%">
                <button type="submit" class="btn btn-primary" style="width: 100%; text-align: center">Submit</button>
            </div>
        </div>
    </div>
}

<script src="https://cdn.tiny.cloud/1/h51q5yt2inxmfi7d3yagm5nofygcwx9dhwo2ujixosmr9yxi/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea#ndBaiViet1',
        plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name'
    });
</script>